recite_dict:
    resource: "@ReciteMainBundle/Controller/"
    type:     annotation
    prefix:   /

recite_data:
    resource: "@ReciteDataBundle/Controller/"
    type:     annotation
    prefix:   /

recite_user:
    resource: "@ReciteUserBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults: {_controller: ReciteUserBundle:Security:login}

login_check:
    path: /login_check

logout:
    path: /logout